apiVersion: v1
kind: Secret
metadata:
  name: loomi-secrets
  namespace: loomi
type: Opaque
data:
  # Base64编码的密钥
  # 使用命令生成: echo -n "your-secret-value" | base64
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleQ==
  master-key: eW91ci1tYXN0ZXIta2V5
  
  # API密钥
  openai-api-key: eW91ci1vcGVuYWktYXBpLWtleQ==
  claude-api-key: eW91ci1jbGF1ZGUtYXBpLWtleQ==
  gemini-api-key: eW91ci1nZW1pbmktYXBpLWtleQ==
  
  # 数据库配置
  supabase-url: aHR0cHM6Ly9zdXBhYmFzZS1wcm9qZWN0LnN1cGFiYXNlLmNv
  supabase-key: eW91ci1zdXBhYmFzZS1rZXk=
  
  # Redis配置
  redis-password: eW91ci1yZWRpcy1wYXNzd29yZA==
  
  # 告警配置
  feishu-webhook-url: aHR0cHM6Ly9vcGVuLmZlaXNodS5jbi9vcGVuYXBpL3dlYmhvb2s=
  smtp-password: eW91ci1zbXRwLXBhc3N3b3Jk
  
  # OSS配置
  oss-access-key-id: eW91ci1vc3MtYWNjZXNzLWtleS1pZA==
  oss-access-key-secret: eW91ci1vc3MtYWNjZXNzLWtleS1zZWNyZXQ=
  
  # 百度AI配置
  baidu-api-key: eW91ci1iYWlkdS1hcGkta2V5
  baidu-secret-key: eW91ci1iYWlkdS1zZWNyZXQta2V5

---
apiVersion: v1
kind: Secret
metadata:
  name: loomi-dev-secrets
  namespace: loomi-dev
type: Opaque
data:
  # 开发环境密钥
  jwt-secret: ZGV2LWp3dC1zZWNyZXQta2V5
  master-key: ZGV2LW1hc3Rlci1rZXk=
  
  # 开发环境API密钥（可以使用测试密钥）
  openai-api-key: ZGV2LW9wZW5haS1hcGkta2V5
  claude-api-key: ZGV2LWNsYXVkZS1hcGkta2V5
  gemini-api-key: ZGV2LWdlbWluaS1hcGkta2V5
